/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CelularController;
import Model.Celular;
import Model.Plan;
import tools.Pantalla;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author wilia
 */
public class IngresoCelular extends javax.swing.JFrame {

    Icono icono = new Icono();
    MenuPrincipal menuPrincipal;
    Pantalla pantalla = Pantalla.getInstance();
    CelularController celularC;
    
    public IngresoCelular() {
        initComponents();
        campoColor.requestFocusInWindow();
        icono.setImageToLabel(iconoCelular, "src/main/java/imagenes/iconoCelular.png");
        icono.setImageToLabel(botonAtras, "src/main/java/imagenes/iconoAtras.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoPlan = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        campoNumeroCelular = new javax.swing.JTextField();
        campoPrecioCosto = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        iconoCelular = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        campoModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoMarca = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        campoColor = new javax.swing.JComboBox<>();
        campoPrecioVenta = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        campoIMEI = new javax.swing.JTextField();
        campoCodigoBarra = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        botonAtras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 38, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 208, 235));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESE DATOS DEL CELULAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 680, 50));

        campoPlan.setForeground(new java.awt.Color(0, 0, 0));
        campoPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PREPAGO", "POSTPAGO" }));
        jPanel1.add(campoPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 161, 46));

        jSeparator1.setBackground(new java.awt.Color(190, 208, 235));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 280, 10));

        jSeparator2.setBackground(new java.awt.Color(190, 208, 235));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 280, 10));

        jSeparator3.setBackground(new java.awt.Color(190, 208, 235));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 280, 13));

        campoNumeroCelular.setBackground(new java.awt.Color(17, 38, 53));
        campoNumeroCelular.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoNumeroCelular.setForeground(new java.awt.Color(190, 208, 235));
        campoNumeroCelular.setText("NUMERO CELULAR");
        campoNumeroCelular.setBorder(null);
        campoNumeroCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNumeroCelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumeroCelularFocusLost(evt);
            }
        });
        campoNumeroCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroCelularActionPerformed(evt);
            }
        });
        jPanel1.add(campoNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 270, 50));

        campoPrecioCosto.setBackground(new java.awt.Color(17, 38, 53));
        campoPrecioCosto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoPrecioCosto.setForeground(new java.awt.Color(190, 208, 235));
        campoPrecioCosto.setText("PRECIO COSTO");
        campoPrecioCosto.setBorder(null);
        campoPrecioCosto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPrecioCostoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPrecioCostoFocusLost(evt);
            }
        });
        campoPrecioCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecioCostoActionPerformed(evt);
            }
        });
        jPanel1.add(campoPrecioCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 280, 50));

        jSeparator5.setBackground(new java.awt.Color(190, 208, 235));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 280, 10));
        jPanel1.add(iconoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 180, 150));

        botonGuardar.setBackground(new java.awt.Color(51, 153, 255));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        botonGuardar.setText("GUARDAR");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 180, 60));

        jSeparator4.setBackground(new java.awt.Color(190, 208, 235));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 280, 10));

        campoModelo.setBackground(new java.awt.Color(17, 38, 53));
        campoModelo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoModelo.setForeground(new java.awt.Color(190, 208, 235));
        campoModelo.setText("MODELO");
        campoModelo.setBorder(null);
        campoModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoModeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoModeloFocusLost(evt);
            }
        });
        campoModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoModeloMouseClicked(evt);
            }
        });
        campoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModeloActionPerformed(evt);
            }
        });
        jPanel1.add(campoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 280, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 208, 235));
        jLabel4.setText("PLAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 107, 38));

        campoMarca.setBackground(new java.awt.Color(17, 38, 53));
        campoMarca.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoMarca.setForeground(new java.awt.Color(190, 208, 235));
        campoMarca.setText("MARCA");
        campoMarca.setBorder(null);
        campoMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoMarcaFocusLost(evt);
            }
        });
        campoMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoMarcaMouseClicked(evt);
            }
        });
        campoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(campoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 280, 50));

        jSeparator8.setBackground(new java.awt.Color(190, 208, 235));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 280, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(190, 208, 235));
        jLabel5.setText("COLOR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 107, 38));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 280, 10));

        campoColor.setForeground(new java.awt.Color(0, 0, 0));
        campoColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BLANCO", "NEGRO", "AZUL", "OTRO" }));
        jPanel1.add(campoColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 161, 46));

        campoPrecioVenta.setBackground(new java.awt.Color(17, 38, 53));
        campoPrecioVenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoPrecioVenta.setForeground(new java.awt.Color(190, 208, 235));
        campoPrecioVenta.setText("PRECIO VENTA");
        campoPrecioVenta.setBorder(null);
        campoPrecioVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPrecioVentaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPrecioVentaFocusLost(evt);
            }
        });
        campoPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrecioVentaActionPerformed(evt);
            }
        });
        jPanel1.add(campoPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 270, 50));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 280, 10));

        campoIMEI.setBackground(new java.awt.Color(17, 38, 53));
        campoIMEI.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoIMEI.setForeground(new java.awt.Color(190, 208, 235));
        campoIMEI.setText("IMEI");
        campoIMEI.setBorder(null);
        campoIMEI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoIMEIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoIMEIFocusLost(evt);
            }
        });
        campoIMEI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoIMEIMouseClicked(evt);
            }
        });
        campoIMEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIMEIActionPerformed(evt);
            }
        });
        jPanel1.add(campoIMEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 270, 40));

        campoCodigoBarra.setBackground(new java.awt.Color(17, 38, 53));
        campoCodigoBarra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        campoCodigoBarra.setForeground(new java.awt.Color(190, 208, 235));
        campoCodigoBarra.setText("CODIGO BARRA");
        campoCodigoBarra.setBorder(null);
        campoCodigoBarra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCodigoBarraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodigoBarraFocusLost(evt);
            }
        });
        campoCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoBarraActionPerformed(evt);
            }
        });
        jPanel1.add(campoCodigoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 260, 40));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 280, 10));

        botonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAtrasMouseClicked(evt);
            }
        });
        jPanel1.add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1099, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPrecioCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecioCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecioCostoActionPerformed

    private void campoPrecioCostoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPrecioCostoFocusLost
       if(campoPrecioCosto.getText().isBlank()){
           campoPrecioCosto.setText("PRECIO COSTO");
       }
    }//GEN-LAST:event_campoPrecioCostoFocusLost

    private void campoPrecioCostoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPrecioCostoFocusGained
        campoPrecioCosto.setText("");
    }//GEN-LAST:event_campoPrecioCostoFocusGained

    private void campoNumeroCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroCelularActionPerformed

    private void campoNumeroCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroCelularFocusLost
        if(campoNumeroCelular.getText().isBlank()){
           campoNumeroCelular.setText("NUMERO CELULAR");
       }
    }//GEN-LAST:event_campoNumeroCelularFocusLost

    private void campoNumeroCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumeroCelularFocusGained
        campoNumeroCelular.setText("");
    }//GEN-LAST:event_campoNumeroCelularFocusGained

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered
        Color customColor = new Color(153,204,255); 
        botonGuardar.setBackground(customColor);
    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited
        Color customColor = new Color(51,153,255); 
        botonGuardar.setBackground(customColor);
    }//GEN-LAST:event_botonGuardarMouseExited

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        JOptionPane.showMessageDialog(null, "Celular guardado exitosamente");
        guardarCelular();
        pantalla.abrirPantalla(menuPrincipal = new MenuPrincipal(),1100,700);
        this.dispose();
    }//GEN-LAST:event_botonGuardarMouseClicked

    private void campoModeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoModeloFocusGained
        campoModelo.setText("");
    }//GEN-LAST:event_campoModeloFocusGained

    private void campoModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoModeloFocusLost
        if(campoModelo.getText().isBlank()){
           campoModelo.setText("MODELO");
       }
    }//GEN-LAST:event_campoModeloFocusLost

    private void campoModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoModeloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModeloMouseClicked

    private void campoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModeloActionPerformed

    private void campoMarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMarcaFocusGained
        campoMarca.setText("");
    }//GEN-LAST:event_campoMarcaFocusGained

    private void campoMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoMarcaFocusLost
        if(campoMarca.getText().isBlank()){
           campoMarca.setText("MARCA");
       }
    }//GEN-LAST:event_campoMarcaFocusLost

    private void campoMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoMarcaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMarcaMouseClicked

    private void campoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMarcaActionPerformed

    private void campoPrecioVentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPrecioVentaFocusGained
        campoPrecioVenta.setText("");
    }//GEN-LAST:event_campoPrecioVentaFocusGained

    private void campoPrecioVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPrecioVentaFocusLost
        if(campoPrecioVenta.getText().isBlank()){
           campoPrecioVenta.setText("PRECIO VENTA");
       }
    }//GEN-LAST:event_campoPrecioVentaFocusLost

    private void campoPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrecioVentaActionPerformed

    private void campoIMEIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIMEIFocusGained
        campoIMEI.setText("");
    }//GEN-LAST:event_campoIMEIFocusGained

    private void campoIMEIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIMEIFocusLost
        if(campoIMEI.getText().isBlank()){
           campoIMEI.setText("IMEI");
       }
    }//GEN-LAST:event_campoIMEIFocusLost

    private void campoIMEIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoIMEIMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIMEIMouseClicked

    private void campoIMEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIMEIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIMEIActionPerformed

    private void campoCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoBarraActionPerformed

    private void campoCodigoBarraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoBarraFocusLost
        if(campoCodigoBarra.getText().isBlank()){
            campoCodigoBarra.setText("CODIGO BARRA");
        }else {
            CelularController celularController = new CelularController();
            llenarCampos();
        }

    }//GEN-LAST:event_campoCodigoBarraFocusLost

    private void campoCodigoBarraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodigoBarraFocusGained
        campoCodigoBarra.setText("");
        campoMarca.setEnabled(true);
        campoModelo.setEnabled(true);
        campoColor.setEnabled(true);
        campoPlan.setEnabled(true);
        campoMarca.setText("MARCA");
        campoModelo.setText("MODELO");
    }//GEN-LAST:event_campoCodigoBarraFocusGained

    private void botonAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAtrasMouseClicked
        Pantalla pantalla = Pantalla.getInstance();
        pantalla.abrirPantalla(menuPrincipal = new MenuPrincipal(), 1100, 700);
        this.dispose();
    }//GEN-LAST:event_botonAtrasMouseClicked


    private int obtenerPlan(){
        String planSeleccionado = campoPlan.getSelectedItem().toString();
        if (planSeleccionado.equals("PREPAGO")){
            return 1;
        }else if (planSeleccionado.equals("POSTPAGO")){
            return 2;
        }
        return 0;
    }

    public void guardarCelular(){
        String codigoBarra = campoCodigoBarra.getText();
        String IMEI = campoIMEI.getText();
        String marca = campoMarca.getText();
        double precioCosto = Double.parseDouble(campoPrecioCosto.getText());
        String modelo =  campoModelo.getText();
        double precioVenta = Double.parseDouble(campoPrecioVenta.getText());
        String colorSeleccionado = campoColor.getSelectedItem().toString();
        String numeroCelular = campoNumeroCelular.getText();
        int plan = obtenerPlan();
        Celular celular = new Celular(codigoBarra, modelo, marca, colorSeleccionado, numeroCelular,
                precioCosto, precioVenta, IMEI,true);
        celularC = new CelularController();
        celularC.guardarCelular(celular, plan);
    }

    public void llenarCampos(){
        Object[] celular = new CelularController().buscarCelular(campoCodigoBarra.getText());
        if (celular != null) {
            String marca = (String) celular[1];
            String modelo = (String) celular[2];
            String color = (String) celular[3];
            String plan = (String) celular[4];
            campoMarca.setText(marca);
            campoModelo.setText(modelo);
            campoColor.setSelectedItem(color);
            campoPlan.setSelectedItem(plan);
            campoMarca.setEnabled(false);
            campoModelo.setEnabled(false);
            campoColor.setEnabled(false);
            campoPlan.setEnabled(false);
        }
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoCelular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonAtras;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoCodigoBarra;
    private javax.swing.JComboBox<String> campoColor;
    private javax.swing.JTextField campoIMEI;
    private javax.swing.JTextField campoMarca;
    private javax.swing.JTextField campoModelo;
    private javax.swing.JTextField campoNumeroCelular;
    private javax.swing.JComboBox<String> campoPlan;
    private javax.swing.JTextField campoPrecioCosto;
    private javax.swing.JTextField campoPrecioVenta;
    private javax.swing.JLabel iconoCelular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
